export const projects = [
  {
    id: 1,
    order: 1,
    filter: "architecture",
    title: "2.1.1 &nbsp; Public Transport Station",
    type: "New Built",
    year: 2023,
    location: "Thessaloniki, Greece",
    direction: "USP",
    description:
      "Almyros Resort is a 5star luxury resort hotel in Northern Corfu, Greece, near the Natura area of the famous sand dunes. The proposal suggests a 75 room hotel with 13 separate room buildings, 3 common buildings, 2 common swimming pools, reaching nearly 7000sqm of built area.",
    picUrl1: "projects-data/white.webp",
    picUrl2: "projects-data/white.webp",
    projectUrl: "projects-view/default.html",
  },
  {
    id: 2,
    order: 2,
    filter: "architecture",
    title: "2.2.1 &nbsp; Almyros Resort",
    type: "New Built",
    year: 2023,
    location: "Corfu, Greece",
    direction: "USP",
    description:
      "Almyros Resort is a 5star luxury resort hotel in Northern Corfu, Greece, near the Natura area of the famous sand dunes. The proposal suggests a 75 room hotel with 13 separate room buildings, 3 common buildings, 2 common swimming pools, reaching nearly 7000sqm of built area.",
    picUrl1: "projects-data/white.webp",
    picUrl2: "projects-data/white.webp",
    projectUrl: "projects-view/default.html",
  },
  {
    id: 3,
    order: 3,
    filter: "architecture",
    title: "2.2.2 &nbsp; EAS Paros",
    type: "Masterplan",
    year: 2022,
    location: "Paros, Greece",
    direction: "USP",
    description:
      "EAS Paros is a Union of Agricultural Cooperatives settled 650m from the coastal line of Paroikia, in Paros Aegean Island, founded in 1929, including a Winery, a Dairy Fram, an oil      Mill, a Barn, a Compost area with a Greenhouse and the Union’s Office space.",
    picUrl1: "projects-data/white.webp",
    picUrl2: "projects-data/white.webp",
    projectUrl: "projects-view/default.html",
  },
  {
    id: 4,
    order: 4,
    filter: "architecture",
    title: "2.2.3 &nbsp; House in Vari",
    type: "New Built",
    year: 2021,
    location: "Athens, Greece",
    direction: "USP",
    description:
      "House in Vari is a 2 storey house with mezzanine, in the seaside region of Vari, in Southeastern Athens. The proposal suggests a pool divided house with a composition of indoor and outdoor spaces, in order to create an introvert house model that multiplies the space within its shell.",
    picUrl1: "projects-data/white.webp",
    picUrl2: "projects-data/white.webp",
    projectUrl: "projects-view/default.html",
  },
  {
    id: 5,
    order: 5,
    filter: "interior",
    title: "3.1.1 &nbsp; Feta Bar",
    type: "Interior",
    year: 2014,
    location: "Thessaloniki, Greece",
    direction: "157+173 designers",
    description:
      "Feta Bar is a dairy shop and gastronomical destination in Thessaloniki center. Kourellas family produces Greek daily since 1960 in the mountains of Grevena. The proposal sets in a 3 storey retail shop, 300m2??, that acts as a vibrant meeting & eating place, around a big table.",
    picUrl1: "projects-data/white.webp",
    picUrl2: "projects-data/white.webp",
    projectUrl: "projects-view/default.html",
  },
  {
    id: 6,
    order: 6,
    filter: "interior",
    title: "3.1.2 &nbsp; Coffee & Roastery in London",
    type: "Interior",
    year: 2016,
    location: "London, United Kingdom",
    direction: "157+173 designers",
    description:
      "House in Vari is a 2 storey house with mezzanine, in the seaside region of Vari, in Southeastern Athens. The proposal suggests a pool divided house with a composition of indoor and outdoor spaces, in order to create an introvert house model that multiplies the space within its shell.",
    picUrl1: "projects-data/white.webp",
    picUrl2: "projects-data/white.webp",
    projectUrl: "projects-view/default.html",
  },
  {
    id: 7,
    order: 7,
    filter: "research",
    title: "5.2.1 &nbsp; Athen's Kiosk",
    type: "Research",
    year: 2021,
    location: "Athens, Greece",
    direction: "USP",
    description:
      "House in Vari is a 2 storey house with mezzanine, in the seaside region of Vari, in Southeastern Athens. The proposal suggests a pool divided house with a composition of indoor and outdoor spaces, in order to create an introvert house model that multiplies the space within its shell.",
    picUrl1: "projects-data/white.webp",
    picUrl2: "projects-data/white.webp",
    projectUrl: "projects-view/default.html",
  },
];
